# Generated by Django 2.2.28 on 2023-06-23 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_hello'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hii',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dsdds', models.BigIntegerField()),
            ],
        ),
    ]
