# Generated by Django 2.2.28 on 2023-06-29 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_hii'),
    ]

    operations = [
        migrations.AddField(
            model_name='hello',
            name='klklkjj',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
