# Generated by Django 2.2.28 on 2023-06-29 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_hello_klklkjj'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hello',
            name='klklkjj',
        ),
        migrations.AddField(
            model_name='hello',
            name='klklkjjrddddds',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hello',
            name='addsdd',
            field=models.BigIntegerField(blank=True),
        ),
    ]
