# Generated by Django 2.2.28 on 2023-06-29 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20230629_1717'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hello',
            name='klklkjjrdd',
        ),
        migrations.AddField(
            model_name='hello',
            name='klklkjjrddkjgg',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
